### ISSUE TITLE
strange wrench sound.

### ISSUE THREAD

**Issue by TheMilso** [Beyond-Reality/BeyondRealityModPack#278] opened 2015-08-14 03:42 UTC
Tested in SP and even deleted and reinstalled pack same result even on new worlds.
Every time i open inventory i get the sound of a wrench shortly after.
No really a game breaking issue but it's driving me nuts.

**Comment by Dyonovan** [comment] 2015-08-14 03:44
Might have to do with Extra Utilities.

https://github.com/Blood-Asp/GT5-Unofficial/issues/130

**Comment by TheMilso** [comment] 2015-08-14 03:45
yea that's the one looks like fix is to downgrade for now.
THANK YOU!!!

**Comment by TheMilso** [comment] 2015-08-14 03:57
yep confirmed downgrading to 1.2.6 and issue is gone.

**Comment by Yann151924** [comment] 2015-08-15 14:12
We have the same bug on our server, i made a special ressource pack to turn off the sound ( it turn off the drill sound,break sound and anvil sound).
You can download it to : http://public.mineaurion.com/Fix-Drill-Sound.zip

**Comment by Dominance** [comment] 2015-08-16 16:10
Thanks a ton yann151924 Im going to include this in the launcher as a optional resource pack

**Comment by Yann151924** [comment] 2015-08-16 16:24
Your welcome the issue is reported on : 

https://github.com/rwtema/extrautilities/issues/671

and on :

https://github.com/Blood-Asp/GT5-Unofficial/issues/130

**Comment by Buuz135** [comment] 2015-09-03 15:03
Can't be fix until RWTema decides to.

**Comment by Dyonovan** [comment] 2015-10-15 15:50
Ok looks like Bloodasp got it fixed in GT. Will be updated later today

**Closed by Dyonovan** 2015-10-15 15:50 UTC
Labels: bug, Priority
