### ISSUE TITLE
Other think for convert rf to eu

### ISSUE THREAD

**Issue by Gohu29** [Beyond-Reality/BeyondRealityModPack#290] opened 2015-09-04 13:09 UTC
I found this today.
![image](https://cloud.githubusercontent.com/assets/13649609/9684202/3bdb0278-5316-11e5-9a4c-6cfcc015e183.png)

And are you aware about this: 
![image](https://cloud.githubusercontent.com/assets/13649609/9684261/a79d9890-5316-11e5-9bf0-bcadbbcf2284.png)

![image](https://cloud.githubusercontent.com/assets/13649609/9684264/b8eb4af2-5316-11e5-8d45-f9ff7e0f8622.png)

When I process Cobblestone in Sag mill I receive sand with akward ID and gravel is rename.

**Comment by Dominance** [comment] 2015-09-24 03:30
Merged pull from leagris that fixes the invalid gravel / sand #293 . Next update will make eu - rf conversion method a priority to fix

**Comment by Dyonovan** [comment] 2015-10-15 15:47
What mod is doing the conversion?

**Comment by leagris** [comment] 2015-10-15 22:30
Galacticraft core Energy beam

**Comment by leagris** [comment] 2015-10-15 23:48
Issue with energy beams even worse than that:
[ Infinite Energy #1842 ](https://github.com/micdoodle8/Galacticraft/issues/1842)

**Comment by spacebuilder2020** [comment] 2015-10-18 01:18
It is a bit more than the energy beam causing the issue... Any galacticraft block causes the issue.

Basically the only way to fix the issue is to modify the class related to energy conversion to not convert back to rf.

**Comment by leagris** [comment] 2015-10-18 02:05
Does it convert back to EU?
Because if it convert back everything to RF, it is not an issue.

**Comment by spacebuilder2020** [comment] 2015-10-18 02:46
Yep

**Comment by spacebuilder2020** [comment] 2015-10-18 02:46
However, with the current screwup (ie setting Galacticraft Jules to RF conversion rate to 0), 1 eu is equal to near infinite RF.

**Comment by spacebuilder2020** [comment] 2015-10-18 02:47
The problem with galacticraft is internally, it does not use RF or eu.  It uses it's own internal power system based on universal electricity Jules.

**Comment by leagris** [comment] 2015-10-18 17:15
Opened a specific issue in Galacticraft
https://github.com/micdoodle8/Galacticraft/issues/1894

**Comment by spacebuilder2020** [comment] 2015-10-18 19:42
I am going to look into writing a mini mod that would give more control over conversion.

**Closed** 2015-10-25 00:10 UTC
Labels: Priority

**Comment by leagris** [comment] 2015-10-25 00:14
Fix in next update

**Comment by spacebuilder2020** [comment] 2015-10-25 16:57
Found a typo in the code... It has been fixed in https://github.com/micdoodle8/Galacticraft/pull/1910, but we will need to update.
