### ISSUE TITLE
Gregtech centrifuges no longer process Forestry products

### ISSUE THREAD

**Issue by leagris** [Beyond-Reality/BeyondRealityModPack#238] opened 2015-06-10 00:41 UTC
Since update to BeyondReality 2.3.0a, no products from Forestry can be processed in GregTech machines in replacement of Forestry machines.

**Comment by Dyonovan** [comment] 2015-06-10 00:42
Duplicate of #237

**Closed by Dyonovan** 2015-06-10 00:42 UTC
Labels: duplicate
