### ISSUE TITLE
Forestry .cfg files are empty

### ISSUE THREAD

**Issue by ohlookitsben** [Beyond-Reality/BeyondRealityModPack#258] opened 2015-06-27 06:34 UTC
Causes a crash on beekeeper villager generation due to empty vanilla flower map.

Crash Report:
https://gist.github.com/ohlookitsben/61573f09bbb614ee1411

Spoke with mezz and was informed that the configs wont work if they're empty.
Example apiculture.cfg
https://gist.github.com/mezz/ef7e5776070babaaef50

Other notes:
Build 601 of Forestry does not cause this issue. Configs were changed in builds after this. Have not tested with cfg provided by mezz as using 601 allowed the village to complete generation, and crash no longer occurs (since the village is generated already) even when Forestry is reverted to 606.

**Comment by mezz** [comment] 2015-06-27 06:42
The config exposes everything now, so if you remove everything than the bees have no valid flowers.
If you give Forestry an old apiculture.conf it will convert it to the new format automatically.

**Comment by mezz** [comment] 2015-06-28 21:00
This may have been caused by an issue with non-english locales. 
If the system language uses commas for decimal separator, it would generate a blank config, which Beyond Reality then packaged as the default.
I pushed a fix today in unstable build 620, I need some people with different system languages to try it out.

**Comment by Buuz135** [comment] 2015-06-29 11:05
Fixed in 2.3.2

**Closed by Buuz135** 2015-06-29 11:05 UTC
